### ISSUE TITLE
Income fixes

### ISSUE THREAD

**Issue by dannychapman** [adhocteam/lunchux#140]
- [x] Update language to better mesh with yes / no questions
- [x] Yes no radio button styles should match style of other yes no radio buttons
- [x] Income sections show as complete before anything has been entered - needs a new "incomplete" state, and associated styling
- [x] Forms for each household member should open after each previous one has been completed. 
- [x] Income section does not have form error validation messages

**Comment by dannychapman** [comment]
Some of this will require development tasks - feel free to break out.

**Comment by dannychapman** [comment]
<img width="655" alt="screen shot 2016-02-28 at 8 20 08 pm" src="https://cloud.githubusercontent.com/assets/281709/13383639/8dc6734a-de5a-11e5-9f0c-5bcba1250af6.png">

**Comment by paulsmith** [comment]
#144 addressed the 'incomplete' state -- anything else to do here?

**Comment by dannychapman** [comment]
@paulsmith incomplete should be on a person by person basis, rather than the whole form. Otherwise I think we are set here.

**Comment by paulsmith** [comment]
OK fixing now

**Comment by greggersh** [comment]
Also, don't default to 0.

**Comment by paulsmith** [comment]
@greggersh Yep, got it -- commit coming soon.

**Comment by paulsmith** [comment]
Remaining issues fixed by 818a9ab.
