### ISSUE TITLE
Break up family review sections into panels

### ISSUE THREAD

**Issue by dannychapman** [adhocteam/lunchux#147]
![screen shot 2016-02-29 at 9 26 57 am](https://cloud.githubusercontent.com/assets/281709/13397143/9f33641e-dec6-11e5-9c99-5e515e1d6dca.png)

**Comment by phiden** [comment]
@dannychapman by panels you mean the grey background? 
<img width="707" alt="screen shot 2016-02-29 at 11 30 12 am" src="https://cloud.githubusercontent.com/assets/4895604/13400880/d538dd1c-ded7-11e5-843c-c0078e8aa7f0.png">
