### ISSUE TITLE
Edit button on #review > adult goes nowhere

### ISSUE THREAD

**Issue by phiden** [adhocteam/lunchux#151]

**Comment by paulsmith** [comment]
I can't recreate this -- to be clear, you're talking about this link, right?
![square meal 2016-02-29 11-50-16](https://cloud.githubusercontent.com/assets/1210/13403438/a3d92436-deda-11e5-9aff-5d924f40f00d.jpg)

**Comment by phiden** [comment]
Yes, that's the one

**Comment by phiden** [comment]
But on the adult summary, not the kids.

**Comment by paulsmith** [comment]
Ah, whoops. But still can't recreate:
![square meal 2016-02-29 11-58-34](https://cloud.githubusercontent.com/assets/1210/13403682/d05136ec-dedb-11e5-96cb-9d27d53ef8b5.jpg)

**Comment by paulsmith** [comment]
And clicking that takes me to `#adults`
