### ISSUE TITLE
connect FAQ prompts to the FAQ itself

### ISSUE THREAD

**Issue by phiden** [adhocteam/lunchux#33]

**Comment by phiden** [comment]
Not sure how to best approach this -- was thinking I'd convert all the current FAQ prompts into <a> tags targeting an ID in the FAQ, but that breaks the view setter. Any guidance, @paulsmith?

**Comment by paulsmith** [comment]
Couple of approaches.

We could make FAQ it's own actual full HTML page, in which case anchors would just work.

We could make the hash hierarchical, so for example `#faq:some-question` would be split on the `:` by the view setter and the second part could be used to highlight/scroll to the ID.

We could make the FAQ purely virtual and dynamically select the answers into the FAQ prompts, on hover or click.

Tradeoffs to each approach I could get into more detail about ...

**Comment by phiden** [comment]
Looks like we've effectively rendered this moot by using modals instead of links to FAQ.
