### ISSUE TITLE
Continue button should be default disabled unless the entire form is valid

### ISSUE THREAD

**Issue by phiden** [adhocteam/lunchux#38]

**Comment by dannychapman** [comment]
@phiden Does this apply to the http://localhost:8000/#kids page? Seems like the continue button should be disabled until information is filled out for all kids.

**Comment by phiden** [comment]
@dannychapman probably right -- this was a note from something I think @paulsmith said in yesterday's call; he might have more insight?

**Comment by paulsmith** [comment]
Yes this is meant for all screens/pages.
