### ISSUE TITLE
Nav isn't working consistently

### ISSUE THREAD

**Issue by phiden** [adhocteam/lunchux#48]
After pulling all the new code, the nav bar across the top is breaking. 

```
setting view 'income'
app.js:986 Uncaught TypeError: Cannot read property 'get-started' of undefined(anonymous function) @ app.js:986Controller.setActiveNavTab @ app.js:973Controller.loadView @ app.js:942loadView @ app.js:1053(anonymous function) @ app.js:1057
app.js:915 setting view 'kids'
app.js:966 Uncaught TypeError: Cannot set property 'income' of undefinedController.markComplete @ app.js:966Controller.loadView @ app.js:936loadView @ app.js:1053
app.js:915 setting view 'other-help'
app.js:966 Uncaught TypeError: Cannot set property 'kids' of undefined
```

**Comment by phiden** [comment]
Looks like whatever's happening has also taken out the back/continue buttons. Clicking those doesn't throw an error, but also doesn't advance the app.

**Comment by paulsmith** [comment]
I think this is because you have data saved from a previous session that doesn't have what the new code needs. Can you delete `lunchux` from your `localStorage`? (In Chrome, this is dev tools -> Resources -> Local Storage -> toggle arrow -> click on localhost -> delete `lunchux` key.)

**Comment by phiden** [comment]
Yup, that was it. Thanks!
