### ISSUE TITLE
Text on children page makes an assumption about children that hasn't been answered yet

### ISSUE THREAD

**Issue by dannychapman** [adhocteam/lunchux#58]
You've told us you have 1 kid under 18 in the household. We're going to collect some information that will help your school determine eligibility for free & reduced lunch.

^^ First page, you only answer that you're over 21. Also, curious - is 21 a requirement for using the app? Seems odd to have that as the age requirement for a parent.

**Comment by phiden** [comment]
- [ ] change language from 'over 21' to 'an adult'
