### ISSUE TITLE
Definition links could be inline with content

### ISSUE THREAD

**Issue by dannychapman** [adhocteam/lunchux#59]
![screen shot 2016-02-24 at 10 57 29 am](https://cloud.githubusercontent.com/assets/281709/13291365/714e4fb2-dae5-11e5-83d1-657ffcec812d.png)

Rather than block links for each, consider just contextual links as each term is mentioned in the previous bullet list.

**Comment by phiden** [comment]
Is that obvious enough? I worry that people would miss them and end up confused.

**Comment by dannychapman** [comment]
@phiden I think if we style them heavily it is.
