### ISSUE TITLE
Flip 'continue' and 'go back' buttons on mobile

### ISSUE THREAD

**Issue by phiden** [adhocteam/lunchux#88]

**Comment by dannychapman** [comment]
For this, we should see what we can do with source ordering in bourbon, and also consider 50 / 50 width

**Comment by phiden** [comment]
50/50 width meaning putting the radio buttons side by side?

**Comment by dannychapman** [comment]
The continue and back buttons? yeah.

**Comment by phiden** [comment]
Yes, those, sorry. Brain fart.
