### ISSUE TITLE
New screen: race/ethnicity, contact, legalese

### ISSUE THREAD

**Issue by phiden** [adhocteam/lunchux#93]

**Comment by phiden** [comment]
Template's in branch new-screen whenever you're ready for it, @paulsmith.

**Comment by paulsmith** [comment]
👍

**Comment by paulsmith** [comment]
- [ ] Move race + ethnicity out of Person model into global model
- [ ] Move race + ethnicity form out of kid details to contact screen
- [ ] Implement ContactView and handle form edits
